# Generated by Django 5.0.3 on 2024-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=100, null=True)),
                ('renter_contact', models.CharField(max_length=100, null=True)),
                ('car_type', models.CharField(choices=[('SUV', 'SUV'), ('EV', 'EV'), ('Truck', 'Truck'), ('Sedan', 'Sedan')], max_length=100, null=True)),
                ('car_model', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
