# Generated by Django 5.0.3 on 2024-04-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0004_carorders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(default='img/lambo.png', upload_to='car_images'),
        ),
    ]
