# Generated by Django 5.0.3 on 2024-04-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0005_cardetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(default='static/img/lambo.png', upload_to='static/img/car_images'),
        ),
    ]
