# Generated by Django 5.0.3 on 2024-04-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0006_alter_cardetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(default='static/img/lambo.jpg', upload_to='static/img/car_images'),
        ),
    ]
