# Generated by Django 5.0.3 on 2024-04-12 04:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0008_rename_date_carorders_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDetails',
            new_name='CarDetail',
        ),
        migrations.RenameModel(
            old_name='CarOrders',
            new_name='CarOrder',
        ),
    ]
