# Generated by Django 5.0.3 on 2024-04-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0009_rename_cardetails_cardetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vroom_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carorder',
            name='rentee_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='renter_contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
