# Generated by Django 5.0.3 on 2024-04-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0010_distributor_vroom_user_carorder_rentee_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='Vroom_User',
        ),
    ]
