# Generated by Django 5.0.3 on 2024-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0011_delete_distributor_delete_vroom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carorder',
            old_name='rentee_name',
            new_name='rentee_email',
        ),
        migrations.RemoveField(
            model_name='carorder',
            name='number_of_days',
        ),
        migrations.AlterField(
            model_name='carorder',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='carorder',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
