# Generated by Django 5.0.3 on 2024-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0014_alter_cardetail_availability_alter_carorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='availability',
            field=models.CharField(choices=[('Unlisted', 'Unlisted'), ('Booked', 'Booked'), ('Available', 'Available')], default='Available', max_length=20, null=True),
        ),
    ]
