# Generated by Django 5.0.3 on 2024-04-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='image',
            field=models.ImageField(default='static/img/profileicon.png', upload_to='static/img/user_images'),
        ),
        migrations.AddField(
            model_name='vroom_user',
            name='image',
            field=models.ImageField(default='static/img/profileicon.png', upload_to='static/img/user_images'),
        ),
    ]
