# Generated by Django 5.0.3 on 2024-05-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0002_distributor_image_vroom_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vroom_user',
            name='license_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
