# Generated by Django 5.0.3 on 2024-05-10 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0003_distributor_location_vroom_user_license_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vroom_user',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vroom_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
